### ISSUE TITLE
How are the conditional probabilities computed?

### ISSUE THREAD

**Issue by Datseris** [kahaaga/CausalityTools.jl#124]
Hi,

this is not really a question about the software per se, but something I want to understand about the method used here.

The joint probability participating in the formula for the transfer entropy is calculated by simply binning the three variables as if they were a 3-dimensional dataset, and calculating the probabilities by "counting".

How is this done for the *conditional probabilities* that are necessary for the transfer entropy?

**Comment by kahaaga** [comment]
For the binning-based estimators, the key to computing the conditional probabilities require for transfer entropy is to express the transfer entropy as conditional mutual information. Then, decompose the conditional mutual information it until you're left with only joint probabilities over subsets of the marginal embedding axes. This way, you don't actually have to explicitly compute conditional probabilities. 

I made a small [pdf](https://github.com/kahaaga/CausalityTools.jl/files/4133892/explanation.1.pdf) with detailed pseudo-code for the `VisitationFrequency` estimator. I hope that helps! 

The other binning-based estimators (e.g. `TransferOperatorGrid`) work in similar ways, but estimate the invariant densities over the grid in different ways. See [Diego et al. (2018)](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.99.042212) for explanations on how the transfer operator approach works.

**Comment by Datseris** [comment]
Thanks a lot, this is very enlightening. So in principle every method may have a different way to compute the conditional probabilities!

**Comment by kahaaga** [comment]
> So in principle every method may have a different way to compute the conditional probabilities!

Yup 👍
